version: '3.8'

services:
  backend:
    build: ./services/users-service
    ports:
      - "5000:5000"
  
  frontend:
    build: ./services/users-service/nodejs-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend